---
# Source: drupal/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: drupal-openshift
  labels:
    app: drupal-openshift
    chart: drupal-6.2.2
    release: "RELEASE-NAME"
    heritage: "Helm"
type: Opaque
data:
  
  drupal-password: "ZHJ1cGFsMTIzNDU2"
